version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - src-db:/var/lib/postgresql/data
  api:
    image: js-express-api
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app

  web-cli:
    image: js-express-api
    networks:
      - backend
    command: sh

volumes:
  src-db:


networks:
  backend:
    driver: bridge
