version: '3'
services:
  api:
    image: js-express-api
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app

  web-cli:
    image: js-express-api
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
