const _ = require('lodash');
const fs = require('fs');
const { google } = require('googleapis');
const { getIterationStories } = require('./../shortcut/shortcut');
require('./../shortcut/shortcut')
require('dotenv').config();
require("./google-oauth-generate-url")

async function getAuth() {
  //Oauth that reads from google-client-secret.json, which is generated by Google Cloud API Credentials page
  const redirectUris = ['http://localhost:3000', 'http://localhost:3000/success']
  const oAuth2Client = new google.auth.OAuth2(
    process.env.GOOGLE_CLIENT_ID, process.env.GOOGLE_CLIENT_SECRET, redirectUris[0],
  );

  //token is generated by google-oauth-get-tokens.js
  const token = fs.readFileSync(`${__dirname}\\google-oauth-token.json`, 'utf-8');
  oAuth2Client.setCredentials(JSON.parse(token));
  return oAuth2Client
};


async function readGoogleSheet() {

  oAuth2Client = await getAuth()
  const sheets = google.sheets({ version: 'v4', auth: oAuth2Client })

  return sheets.spreadsheets.values.get({
    spreadsheetId: `${process.env.GOOGLE_SPREADSHEET_ID}`,
    range: "Sheet1!A2:Z100"
  })
    .then((_.property('data.values')));
};


async function writeGoogleSheet(id) {

  oAuth2Client = await getAuth()
  const sheets = google.sheets({ version: 'v4', auth: oAuth2Client });

  //Spreadsheet ID of our target
  const spreadsheetId = process.env.GOOGLE_SPREADSHEET_ID

  await sheets.spreadsheets.values.append({
    spreadsheetId,
    range: "Sheet1!A:Z",
    valueInputOption: "USER_ENTERED",
    resource: {
      values: [[1, 2, 3, 4, 5]], //this will be an array of arrays from DB on stories we want.
    }
  }).then((res) => {
    console.log(`Status: ${res.status}`);
    return true
  }).catch((err) => {
    console.error(err);
  });

};


async function writeIterationToGoogleSheet() {

  oAuth2Client = await getAuth()
  const sheets = google.sheets({ version: 'v4', auth: oAuth2Client });

  //Spreadsheet ID of our target
  const spreadsheetId = process.env.GOOGLE_SPREADSHEET_ID

  storyArray = await getIterationStories()

  await sheets.spreadsheets.values.append({
    spreadsheetId,
    range: "Sheet1!A:Z",
    valueInputOption: "USER_ENTERED",
    resource: {
      values: storyArray,
    }
  }).then((res) => {
    console.log(`Status: ${res.status}`);
    return true
  }).catch((err) => {
    if (JSON.stringify(err.response.status) == 401){
      console.log('401 unauthorized');
      fs.unlink(`${__dirname}\\google-oauth-token.json`)
    }
  });

};

module.exports = { writeGoogleSheet, getAuth, writeIterationToGoogleSheet }