const _ = require('lodash');
const fs = require('fs');
const { google } = require('googleapis');

//one-time generated from Google Cloud API Credentials page
//https://console.cloud.google.com/apis
const credentials = JSON.parse(fs.readFileSync('google-client-secret.json', 'utf-8'));

const {
  client_secret: clientSecret,
  client_id: clientId,
  redirect_uris: redirectUris,
} = credentials.installed;

//Oauth that reads from google-client-secret.json, which is generated by Google Cloud API Credentials page
const oAuth2Client = new google.auth.OAuth2(
  clientId, clientSecret, redirectUris[0],
);

//token is generated by google-oauth-get-tokens.js
const token = fs.readFileSync('google-oauth-token.json', 'utf-8');
oAuth2Client.setCredentials(JSON.parse(token));


exports.read = async (spreadsheetId, range) => {
  const sheets = google.sheets({ version: 'v4', auth: oAuth2Client });

  return sheets.spreadsheets.values.get({
    spreadsheetId,
    range,
  })
    .then(_.property('data.values'));
};



const spreadsheetId = '1tZH-jH4pXOu13nU1m9WA_FuxranFRd-rBGkEdVptfrQ'

async function writeGoogleSheet(id) {
  

  sheets.spreadsheets.values.append({
    spreadsheetId,
    range: "Sheet2!A:Z", 
    valueInputOption: "USER_ENTERED", 
    resource: {
      values: [[1,2,3,4,5]], //this is actually an array of arrays
    }
  }).then((res) => {
    console.log(`Status: ${res.status}`);
    return true
  }).catch((err) => {
    console.error(err);
  });

};

writeGoogleSheet()